networks:
  k6:

services:
  k6:
    image: grafana/k6:latest
    command: run /scripts/checkout.k6.js
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - BASE_URL=${BASE_URL}
      - REPORTS_PATH=/reports
    volumes:
      - ./k6:/scripts
      - ./reports:/reports
