name: run k6

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  k6-validation:
    runs-on: ubuntu-latest
    steps:
      - name: k6 run
        uses: xdigu/k6-workflow@main
        with:
          base_url: ${{ vars.BASE_URL }}
          should_run_default: true
